# Generated by Django 3.0.7 on 2020-06-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='ad_img'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='ad_img'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='ad_img'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='ad_img'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='ad_img'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_brand',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, choices=[('VEH', 'VEHICLES'), ('ELE', 'ELECTRONICS'), ('FUR', 'FURNITURE'), ('OTH', 'OTHER')], max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_condition',
            field=models.CharField(blank=True, choices=[('BN', 'BRAND NEW'), ('N', 'NEW'), ('U', 'USED'), ('NW', 'NOT WORKING')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_model',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
